### ISSUE TITLE
Windows failed to compile if BUILD_SHARED_LIBS=OFF

### ISSUE THREAD

**Issue by pzhu-flexiv** [jrl-umi3218/RBDyn#106]
On Windows (I'm using MSVC v143 if this information is relevant), if set the cmake option BUILD_SHARED_LIBS to OFF, then the compilation would fail. The errors look like this:
![image](https://github.com/jrl-umi3218/RBDyn/assets/34045850/91359012-2c1c-49ab-979d-c7b1dd3c8110)

After some debugging, I found the root cause is this macro block in **RBDyn**
![image](https://github.com/jrl-umi3218/RBDyn/assets/34045850/546a3904-75c3-4d68-854b-85a9be15484c)
and this macro block in **RBDynParsers**
![image](https://github.com/jrl-umi3218/RBDyn/assets/34045850/d6da7192-e576-4e84-9319-369c2f89b371)
are both NOT properly activated even if BUILD_SHARED_LIBS=OFF, because the macro `RBDYN_STATIC` and `RBDYN_PARSERS_STATIC` are never defined in cmake. This caused the `__declspec(dllimport)` Windows shared library directive to be appended in the compiled static library RBDyn.lib and RBDynParsers.lib, which caused the linker errors.

Making the following changes solved the issue, please review and PR the fix, thanks.
![image](https://github.com/jrl-umi3218/RBDyn/assets/34045850/e5f1a0aa-d522-4171-8dad-ab05ec4b8571)
![image](https://github.com/jrl-umi3218/RBDyn/assets/34045850/eb3cb968-19f1-4fcc-b2bd-e408e4ad65e4)

**Comment by gergondet** [comment]
Hi @pzhu-flexiv 

I think you are using an older version of RBDyn because this was already reported and fixed in https://github.com/jrl-umi3218/RBDyn/commit/22c5dde7b48b0037e106e7901b0611ccd506ae5e
