### ISSUE TITLE
joint angle limits?

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/RBDyn#15]
When creating models can joint limits be specified at the rbdyn level? I'm [following the tutorial](http://nbviewer.jupyter.org/github/jorisv/sva_rbdyn_tutorials/blob/master/MultiBody.ipynb#MultiBodyConfig) and I don't see a mention of them there or when I search the code for "limit".

**Comment by haudren** [comment]
No, joint limits cannot be handled at the model level. The Multibody object only records the kinematic chain information.
To enforce joint limits, you will need to do it at the controller level. There are a few `JointLimitConstraint` in Tasks that should do the job.

**Comment by ahundt** [comment]
thanks for the clarification!
