### ISSUE TITLE
quatToE() memory layout undefined

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/RBDyn#16]
Is [quatToE()](https://github.com/jrl-umi3218/RBDyn/blob/83db71671786648e6048e536b87a9a78a9c66bcb/src/Joint.h#L567) organized in `wxyz` or `xyzw` format? Can the docs/comments be updated to reflect this?

**Comment by gergondet** [comment]
It's `wxyz`. I've added that information to the doxygen.

Thanks for the report.
