### ISSUE TITLE
quatToE() Eigen::Quaternion version

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/RBDyn#17]
I might submit a pull request for an [Eigen::Quaternion](https://eigen.tuxfamily.org/dox/classEigen_1_1Quaternion.html) version of [quatToE()](https://github.com/jrl-umi3218/RBDyn/blob/83db71671786648e6048e536b87a9a78a9c66bcb/src/Joint.h#L567). Would that be accepted and if so, where should I put it? (in case the current version depends on an old version of eigen without Quaternions.)

**Comment by haudren** [comment]
I don't think that a `quatToE` method is necessary. Simply use `Eigen::Quaternion<T>::matrix()` method to convert quaternions into rotation matrices. `quatToE` is here to convert the joint angles of a spherical joint (Length 4 `std::vector<double>`) into a rotation matrix.

**Comment by ahundt** [comment]
I agree per https://github.com/jrl-umi3218/RBDyn/issues/18. Closing.
