### ISSUE TITLE
Define Joint with Rotation or Full Transform

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/RBDyn#18]
The new version of the [Joint constructor](https://github.com/jrl-umi3218/RBDyn/blob/master/src/Joint.h#L93) takes an axis, but [V-REP supplies a transformation matrix between joints](http://www.coppeliarobotics.com/helpFiles/en/regularApi/simGetJointMatrix.htm). I believe this is because V-REP uses joint objects that are placed in the scene graph, and for revolute joints the axis is placed at the origin of the joint object around the Z axis. I think this is similar to how joints are defined in URDF files. Would simply converting the rotation component to angle axis form and using that axis as the Joint constructor parameter work?

To extend the constructor to take a full Eigen matrix converted from the one V-REP supplies, are there any gotchas, suggestions, or other example code I might find useful?

**Comment by haudren** [comment]
No: I think that what you need to do is create joints all with the Z-axis, then use the transformation supplied by V-REP as the one between successive joints.

So:

``` cpp
MultiBodyGraph mbg;
sva::PTransformd transform = fromVREP(vrepTransform):
Joint j(Joint::Revolute, Eigen::Vector3d(0., 0., 1.), true, "my_joint");
Body b0, b1; //Complete this accordingly
mbg.addJoint(j);
mbg.addBody(b0);
mbg.addBody(b1);
mbg.linkBodies("b0", transform, "b1", sva::PTransformd::Identity(), "j");
```

**Comment by ahundt** [comment]
Thanks, good advice! I'll close this if the suggestion works.

**Comment by ahundt** [comment]
Now that I have forward kinematics working with V-REP + Eigen as per https://github.com/jrl-umi3218/Tasks/issues/10, perhaps it makes sense to create a `Conversions.h` either here or in [SpaceVecAlg](https://github.com/jrl-umi3218/SpaceVecAlg) that provides conversion functions from the `PTransform<T>` to `Eigen::Transform<>` aka `Eigen::Affine3d`, and other formats. I suspect that such a conversion to/from the Eigen format would not only be applicable to V-REP but also ROS and many other libraries that use the other convention. 

Just wanted to open the discussion before I implement to see if there is interest and how to proceed!

**Comment by ahundt** [comment]
The key conversions for this were added to [Conversions.h in SpaceVecAlg](https://github.com/jrl-umi3218/SpaceVecAlg/blob/master/src/SpaceVecAlg/Conversions.h) a while ago so I'm closing this.
