### ISSUE TITLE
EulerIntegration step parameter clarification

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/RBDyn#20]
I'm hoping to clarify what the [EulerIntegration](https://github.com/jrl-umi3218/RBDyn/blob/83db71671786648e6048e536b87a9a78a9c66bcb/src/EulerIntegration.h#L41) step parameter means in the typical case, although I know many of the class and algorithm parameters are technically unitless and may work with other units.

Could it be considered a time step in seconds?

**Comment by haudren** [comment]
Yes, `timeStep` is generally a time in seconds. As you noticed, all algorithms are technically unitless, but require a coherent set of units: we only work in SI units. You could theoretically work in milliseconds/milliradians/millimeters but I don't see why you would inflict yourself that much pain.
