### ISSUE TITLE
CoM Jacobian Column Order

### ISSUE THREAD

**Issue by amdshameer** [jrl-umi3218/RBDyn#40]
I know that [rbd::Jacobian::fullJacobian](https://jrl-umi3218.github.io/RBDyn/doxygen/HEAD/a00012.html#ac578c4340a0e3843e0057b935139f611) columns are arranged in the order of [rbd::MultiBody::jointPosInDof](https://jrl-umi3218.github.io/RBDyn/doxygen/HEAD/a00014.html#ab91b005b1346009777820e3cbb81b0c7). Is it the same for CoM Jacobian [rbd::CoMJacobian::CoMJacobian](https://jrl-umi3218.github.io/RBDyn/doxygen/HEAD/a00004.html#a543e4288e57ea2e6447faeede53f53e5)

**Comment by haudren** [comment]
Yes, both jacobians are such that the speed (of the CoM, or an end-effector) can be computed by:
```
spd = jac * qd
```
