### ISSUE TITLE
floating base 

### ISSUE THREAD

**Issue by kiwiwan** [jrl-umi3218/RBDyn#51]
Excuse me! 
I use RBDyn to controll my humanoid robot.I set the torso as a floating base,add ground force,directly use ID to calculate the joint torque.But i derive also has the floating base joint 6 freedom torque,how i use this torque,because the floating base joint not actuators.
Could i director use ID to calculate the  floating base robot's inverse dynamics?

**Comment by haudren** [comment]
Hello,

I am not sure to understand your question. However, the Inverse Dynamics algorithm only computes the inertia matrix and coriolis vector, then solves for the torque. If you want the torque applied on the floating base to be zero, you need to add constraints and solve yourself or use the `Tasks` library. 

Note that if your forces and accelerations are well defined (e.g. obtained from motion capture), you should automatically get zero torque on the floating base.

**Comment by kiwiwan** [comment]
@haudren ,hello.
I want to use RBDyn to let my humanoid robot stand in vrep simulator.In vrep i could  get the ground force,and floating base position and orientation,and joint position.These value is fine.
Could you give me some advice to let my humanoid robot stand in simulation.What feedback controller need?
I use RBDyn controll Ur10 in Vrep very well through M(q)ddq+C(q)=t feedback controller.But it seem not work in floating base humanoid robot.
Would i realization it through use Tasks library?

**Comment by haudren** [comment]
I am sorry, I am not sure I understand you properly, and without knowing what your exact controller is, I can't help you. The Tasks library is designed for tasks-based control of all robots, but especially humanoids in multi-contact.

**Comment by kiwiwan** [comment]
Thanks.I would learn the tasks library.
