### ISSUE TITLE
Bad behaviour of bodyIndexByName?

### ISSUE THREAD

**Issue by vsamy** [jrl-umi3218/RBDyn#64]
Hi,

So i bump into a problem. I somewhat messed up with an external file that has wrong body names in it.
Then, i wanted to get the index by using `mb.bodyIndexByName(wrongName)`.
The thing is that the function actually returns a valid bodyIndex (body 0). 

Is this the desired behaviour? I would rather prefer the program to throw me an error.

Thanks :)

**Comment by gergondet** [comment]
That's intended. You should use `sBodyIndexByName` if you want a throwing version

**Comment by vsamy** [comment]
Oh ok sorry. I though these functions were made for Python bindings as it is written in the files.
