### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by MohamedNor2020** [jrl-umi3218/RBDyn#71]
make: *** No targets specified and no makefile found.  Stop.
this error appears at almost all jrl libraries .and i can find any solution for it .
i was following this tutorial to setup JRL for implemntation at my humonoid 
https://scaron.info/doc/lipm_walking_controller/build.html
 
any help , thanks in advance .

**Comment by gergondet** [comment]
Hi @MohamedNor2020 

Did you run cmake in the build folder? If so, what was the output?

**Comment by MohamedNor2020** [comment]
Thanks @gergondet it has been solved !
