### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [jrl-umi3218/RBDyn#79]
It has been noticed that while using jrl-umi3218/github-actions/build-package-native@master your other-gpg-keys 0x892EA6EE273707C6495A6FB6220D644C64666806 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by gergondet** [comment]
Thanks, but see https://github.com/jrl-umi3218/mc_rtc/issues/148
