### ISSUE TITLE
Questions about Jacobian: do we get the analytical Jacobian by default in RBDyn

### ISSUE THREAD

**Issue by ghost** [jrl-umi3218/RBDyn#84]
Hi all,

As stated in the title, I just want to make sure I will get the analytical Jacobian from the RBDyn, not the geometric Jacobian.

Assume the pose of the robot is given by $P = [x,y,z,r,p,y]^{T}$ (where r,p,y are Euler angles), is the Jacobian we get from RBDyn the same as: \partial{P}/\partial{t} (t is time?).

Many thanks in advance.

**Comment by gergondet** [comment]
Hi @Thompson104 

If I understand the distinction correctly, the analytical jacobian <img src="https://render.githubusercontent.com/render/math?math=J_a"> such that <img src="https://render.githubusercontent.com/render/math?math=\frac{\partial{P}}{\partial{t}} = J_a \dot{q}"> whereas the geometric jacobian<img src="https://render.githubusercontent.com/render/math?math=J_g"> is such that <img src="https://render.githubusercontent.com/render/math?math=v(P) = J_g \dot{q}"> where <img src="https://render.githubusercontent.com/render/math?math=v(P)"> is the spatial velocity of point P in the world frame.

Then, in fact RBDyn computes the geometric jacobian and not the analytical jacobian. I hope this answers your question adequately.

Note: RBDyn convention is to put rotation first so in those formulas <img src="https://render.githubusercontent.com/render/math?math=v(P)"> has the angular velocity first and the linear velocity second.

**Comment by ghost** [comment]
Thank you @gergondet . It really helped.
