### ISSUE TITLE
missing find_package(Boost)

### ISSUE THREAD

**Issue by bsoe-flexiv** [jrl-umi3218/RBDyn#86]
CMakeList.txt is missing find_package(Boost)

**Comment by gergondet** [comment]
Hi @briansoe66 

It's not, it's indirectly in [src/parsers/CMakeLists.txt](https://github.com/jrl-umi3218/RBDyn/blob/master/src/parsers/CMakeLists.txt#L20) via `add_project_dependency` (and in `tests/CMakeLists.txt` where it's also needed)

Are you having some issues with building RBDyn?

**Comment by bsoe-flexiv** [comment]
@gergondet, thanks for the explanation. I had an issue finding boost when cross-compiling, but I the mistake was in my cmake toolchain. RBDyn was not the problem.
