### ISSUE TITLE
SpaceVecAlg compatibility

### ISSUE THREAD

**Issue by bsoe-flexiv** [jrl-umi3218/RBDyn#87]
Which tag/commit of SpaceVecAlg was used, when releasing each RBDyn tag?

**Comment by gergondet** [comment]
Hi @briansoe66 

We do not track this information. The latest release of SpaceVecAlg works with the latest release of RBDyn and vice-versa.

For binary packages available on the Ubuntu mirrors when a new release of SpaceVecAlg is pushed then the packages of RBDyn are rebuilt against this new version (and so-on for RBDyn dependent projects)
