### ISSUE TITLE
static library

### ISSUE THREAD

**Issue by bsoe-flexiv** [jrl-umi3218/RBDyn#88]
Please remove the hard-coded add_library(SHARED) when building RBDyn and RBdyn parser library. User's should be able to specify the library type using -DBUILD_SHARED_LIBS=ON, this is the normal cmake convention.

**Comment by gergondet** [comment]
Hi @briansoe66 

That's a good point. I've created #91 to fix this.

**Comment by bsoe-flexiv** [comment]
Thanks @gergondet !
